//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortfolyo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_About
    {
        public int AboutID { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public string Title { get; set; }
        public string Description2 { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public Nullable<byte> Age { get; set; }
        public string City { get; set; }
        public string Degree { get; set; }
        public string Email { get; set; }
        public string Freelance { get; set; }
    }
}
